name: patient
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.8.346+2023

publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  http: ^0.13.5
  provider: ^6.0.0
  #intl_phone_number_input: ^0.6.0
  google_fonts: ^2.1.0
  fluttertoast: ^8.0.9
  status_alert: ^1.0.0
  shared_preferences: ^2.0.15
  toggle_switch: ^2.0.1
  font_awesome_flutter: ^10.1.0
  flutter_datetime_picker: ^1.5.1
  #location: ^3.0.0
  #geocoder: ^2.0.0
  #date_util: ^0.2.0
  #month_picker_strip: ^0.0.3
  #calendar_strip: ^1.0.7
  multiselect_formfield: ^0.1.7
  badges: ^2.0.3
  #masked_text_input_formatter: 0.0.1
  syncfusion_flutter_pdfviewer: ^20.2.40-beta
  #flutter_full_pdf_viewer: ^1.0.6
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.4
  firebase_analytics: ^10.0.4
  firebase_remote_config: ^3.0.6
  #razorpay_flutter: ^1.2.3
  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.5
  cached_network_image: ^3.2.1
  #splashscreen: ^1.2.0
  json_serializable: ^6.3.1
  get_it: ^7.2.0
  carousel_slider: ^4.1.1
  youtube_player_flutter: ^8.1.0
  flip_card: ^0.6.0
  modal_bottom_sheet: ^2.1.0
  sn_progress_dialog: 1.0.8
  share: ^2.0.4
  #  file_picker: 2.1.5
  flutter_document_picker: ^5.0.1
  photo_view: ^0.14.0
  #country_codes: ^2.0.1
  devicelocale: ^0.5.5
  group_radio_button: ^1.2.0
  package_info: ^2.0.2
  image_picker: ^0.8.3+3
  flutter_typeahead: ^4.0.0
  #fl_chart: 0.12.3
  charts_flutter:
    git:
      url: https://github.com/google/charts.git
      path: charts_flutter
  lottie: ^1.4.1
  tutorial_coach_mark: ^1.2.4
  intl_phone_field: ^2.0.1
  introduction_screen: ^3.0.2
  #dots_indicator: ^1.2.0
  otp_text_field: ^1.1.3
  health: ^3.1.1+1
  percent_indicator: ^4.2.2
  flutter_dotenv: ^5.0.2
  permission_handler: 9.2.0
  get: ^4.3.8
  pausable_timer: ^1.0.0+5
  phone_number: ^0.12.0+1
  flutter_sim_country_code: ^0.1.2
  device_info_plus: ^3.2.2
  #webview_flutter: 2.0.4
  webfeed: ^0.7.0
  pinch_zoom: ^1.0.0
  xml2json: ^5.3.2
  path_provider: ^2.0.2
  super_tooltip: 1.0.1
  flutter_svg: ^0.22.0
  flutter_picker: 2.0.5
  syncfusion_flutter_gauges: ^20.3.57
  flutter_html: 2.2.1
  flutter_custom_tabs: ^1.0.4
  #terra_flutter_bridge: ^0.3.5
  #in_app_update: ^4.0.1
  pinput: ^2.2.21
  flutter_local_notifications: ^12.0.4
  weekday_selector: ^1.1.0
  event: ^2.1.2
  quiver: ^3.1.0
  flutter_inappwebview: ^5.8.0
  dio: ^4.0.0
  #open_file: ^3.2.1

dev_dependencies:
  #test: any
  #flutter_test:
  #  sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - res/images/
    - res/images/dailyCheckIn/
    - res/images/awards/
    - res/.env
    - res/lottiefiles/
  #   - assets/images/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: res/fonts/montserrar-regular.ttf
        - asset: res/fonts/montserrar-semibold.ttf
          weight: 600
        - asset: res/fonts/montserrat-bold.ttf
          weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
