name: patient
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.8.416+2066

publish_to: none

environment:
  sdk: '>=2.18.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  provider: ^6.1.1
  google_fonts: ^5.0.0
  fluttertoast: ^8.2.1
  #status_alert: ^1.0.1
  shared_preferences: ^2.2.2
  toggle_switch: ^2.3.0
  font_awesome_flutter: ^10.5.0
  flutter_datetime_picker_plus: ^2.1.0
  multiselect_formfield: ^0.1.7
  badges: ^3.1.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.6
  firebase_analytics: ^11.4.5
  firebase_remote_config: ^5.4.3
  flutter_linkify: ^6.0.0
  url_launcher: ^6.2.5
  cached_network_image: ^3.4.1
  json_serializable: ^6.7.1
  get_it: ^7.6.7
  carousel_slider: ^5.0.0
  youtube_player_flutter: ^9.1.1
  flip_card: ^0.6.0
  modal_bottom_sheet: ^3.0.0
  sn_progress_dialog: ^1.2.0
  share_plus: ^11.0.0
  file_picker: ^10.1.9
  #flutter_document_picker:
  #  git:
  #    url: https://github.com/TusharKatakdound/flutter_document_picker.git
  #    ref: main
  photo_view: ^0.14.0
  devicelocale: ^0.8.1
  group_radio_button: ^1.2.0
  package_info_plus: ^8.0.2
  image_picker: ^1.1.2
  flutter_typeahead: ^4.1.1
  charts_flutter:
    git:
      url: https://github.com/TusharKatakdound/charts_flutter.git
      path: charts_flutter
      ref: master
  lottie: ^3.3.1
  tutorial_coach_mark: ^1.2.4
  intl_phone_field: ^2.0.1
  introduction_screen: ^3.1.17
  otp_text_field: ^1.1.3
  health: ^12.0.0
  percent_indicator: ^4.2.5
  flutter_dotenv: ^5.2.1
  permission_handler: ^12.0.0+1
  pausable_timer: ^1.0.0+5
  #phone_numbers_parser: ^9.0.3
  #flutter_sim_country_code:
  #  git:
  #    url: https://github.com/TusharKatakdound/flutter_sim_country_code.git
  device_info_plus: ^11.4.0
  pinch_zoom: ^1.0.0
  xml2json: ^5.3.2
  path_provider: ^2.1.1
  super_tooltip: ^1.0.1
  flutter_svg: ^2.0.10+1
  flutter_picker: ^2.0.5
  syncfusion_flutter_pdfviewer: ^29.1.41
  syncfusion_flutter_gauges: ^29.1.41
  syncfusion_flutter_core: ^29.1.41
  flutter_html: ^3.0.0
  flutter_custom_tabs: ^2.4.0
  pinput: ^5.0.1
  flutter_local_notifications: ^19.2.1
  weekday_selector: ^1.1.0
  event: ^2.1.2
  quiver: ^3.1.0
  #flutter_inappwebview: ^6.1.5
  dio: ^5.4.0
  path_provider_windows: ^2.1.0
  webview_flutter: ^4.4.4
  device_region: ^1.4.0

dev_dependencies:
  #test: any
  #flutter_test:
  #  sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.1

dependency_overrides:
  intl: ^0.18.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_plugin_android_lifecycle: ^2.0.28
  #flutter_document_picker: 5.2.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - res/images/
    - res/images/dailyCheckIn/
    - res/images/awards/
    - res/.env
    - res/lottiefiles/
  #   - assets/images/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: res/fonts/montserrar-regular.ttf
        - asset: res/fonts/montserrar-semibold.ttf
          weight: 600
        - asset: res/fonts/montserrat-bold.ttf
          weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
